language: rust

rust:
  - stable
  - beta
  - nightly

cache: cargo

script:
  - cargo test -v
  - cd sfmt-sys && cargo test -v && cd ..
  - [[ $TRAVIS_RUST_VERSION = "nightly" ]] && cd rsfmt && cargo test -v && cd ..

addons:
  apt:
    packages:
      - gcc
