jobs:
  - template: ci/job.yml
    parameters:
      name: Linux
      pool:
        vmImage: 'ubuntu-16.04'

  - template: ci/job.yml
    parameters:
      name: macOS
      pool:
        vmImage: 'macOS-10.14'

  - job: Windows
    strategy:
      matrix:
        stable:
          rust_toolchain: stable
        beta:
          rust_toolchain: beta
        nightly:
          rust_toolchain: nightly
    steps:
      - script: |
          curl -sSf -o rustup-init.exe https://win.rustup.rs
          rustup-init.exe -y --default-toolchain stable
          set PATH=%PATH%;%USERPROFILE%\.cargo\bin
          echo '##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin'
        displayName: install rustup on Windows

      - script: cargo test --verbose
        displayName: run test
