[package]
name = "sfmt"
version = "0.2.3"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]

description = "Rust implementation of SIMD-oriented Fast Mersenne Twister (SFMT)"
documentation = "https://docs.rs/sfmt/"
repository = "https://github.com/termoshtt/rust-sfmt"
keywords = ["random", "rng"]
categories = ["algorithms"]
license = "MIT"

[dependencies]
rand = "0.4"
