[package]
name = "sfmt"
version = "0.1.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]
description = "Rust wrapper of SFMT"
documentation = "https://docs.rs/sfmt/"
repository = "https://github.com/termoshtt/rust-sfmt"
keywords = ["random", "rng"]
categories = ["algorithms"]
license = "MIT"

[dependencies]
rand = "0.4"

[dependencies.sfmt-sys]
path = "sfmt-sys"
version = "0.1.0"
