[package]
name = "sfmt"
version = "0.7.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]
edition = "2018"

description = "Rust implementation of SIMD-oriented Fast Mersenne Twister (SFMT)"
documentation = "https://docs.rs/sfmt/"
repository = "https://github.com/termoshtt/rust-sfmt"
keywords = ["random", "rng"]
categories = ["algorithms"]
license = "MIT"

[features]
default = ["thread_rng"]

# The thread_rng feature requires the rand and getrandom dependencies
thread_rng = ["rand/sys_rng", "getrandom"]

[dependencies]
rand = { version = "0.10", optional = true }
rand_core = "0.10"
getrandom = { version = "0.4", optional = true }

[dev-dependencies]
rand_xorshift = "0.5"
rand_core = "0.10"
paste = "1.0.5"

[package.metadata.release]
no-dev-version = true
